from django.urls import path

from . import views

app_name = "plateformeweb"
urlpatterns = [
    # path(r'^$', views.UserListView.as_view(), name='user_list'),
    path(
        "organization/",
        views.OrganizationListView.as_view(),
        name="organization_list",
    ),
    path(
        "organization/create/",
        views.OrganizationCreateView.as_view(),
        name="organization_create",
    ),
    path(
        "organization/<int:pk>/edit/",
        views.OrganizationEditView.as_view(),
        name="organization_edit",
    ),
    path(
        "organization/<int:pk>/<slug>/",
        views.OrganizationView.as_view(),
        name="organization_detail",
    ),
    path(
        "organization_manager/<int:pk>/",
        views.OrganizationManager,
        name="organization_manager",
    ),
    path("place/", views.PlaceListView.as_view(), name="place_list"),
    path("place/create/",
         views.PlaceCreateView.as_view(),
         name="place_create"),
    path(
        "place/<int:pk>/edit/",
        views.PlaceEditView.as_view(),
        name="place_edit",
    ),
    path(
        "place/<int:pk>/<slug>/",
        views.PlaceView.as_view(),
        name="place_detail",
    ),
    path(
        "condition/create/",
        views.ConditionCreateView.as_view(),
        name="condition_create",
    ),
    path(
        "condition/<int:pk>/edit/",
        views.ConditionEditView.as_view(),
        name="condition_edit",
    ),
    path("activity/",
         views.ActivityListView.as_view(),
         name="activity_list"),
    path(
        "activity/create/",
        views.ActivityCreateView.as_view(),
        name="activity_create",
    ),
    path(
        "activity/<int:pk>/edit/",
        views.ActivityEditView.as_view(),
        name="activity_edit",
    ),
    path(
        "activity/<int:pk>/<slug>/",
        views.ActivityView.as_view(),
        name="activity_detail",
    ),
    path("event/", views.EventListView.as_view(), name="event_list"),
    path("event/create/",
         views.EventCreateView.as_view(),
         name="event_create"),
    path(
        r"^event/cancel_reservation/(?P<token>.+)/",
        views.cancel_reservation,
        name="cancel_reservation",
    ),
    path(
        "event/<int:pk>/book/",
        views.BookingEditView.as_view(),
        name="booking_form",
    ),
    path(
        "event/<int:pk>/edit/",
        views.EventEditView.as_view(),
        name="event_edit",
    ),
    path(
        "event/<int:pk>/<slug>/",
        views.EventView.as_view(),
        name="event_detail",
    ),
    path(
        "massevent/book/",
        views.MassBookingCreateView.as_view(),
        name="mass_event_book",
    ),
]
