# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='needed_organizers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Needed organizers'),
        ),
    ]
