# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-15 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateformeweb', '0002_event_needed_organizers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='needed_organizers',
            field=models.IntegerField(blank=True, default=0, verbose_name='Needed organizers'),
        ),
    ]
