# Generated by Django 2.2 on 2019-04-16 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Activity type')),
                ('slug', models.SlugField(default='')),
                ('description', models.TextField(default='', verbose_name='Activity description')),
                ('picture', models.ImageField(upload_to='activities/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Condition Type')),
                ('resume', models.CharField(default='', max_length=100, verbose_name='Condition resume')),
                ('description', models.TextField(default='', verbose_name='Condition description')),
                ('price', models.IntegerField(blank=True, default=5, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Title')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date and time')),
                ('slug', models.SlugField(default='', unique=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date and time')),
                ('ends_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date and time')),
                ('available_seats', models.IntegerField(blank=True, default=0, verbose_name='Available seats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
