# Generated by Django 2.2 on 2019-04-18 15:04

import ateliersoude.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(default="")),
                (
                    "place_type",
                    models.CharField(default="Other", max_length=100),
                ),
                ("slug", models.SlugField(blank=True, default="")),
                (
                    "address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="places/",
                        validators=[ateliersoude.utils.validate_image],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
